services:
  app:
    image: no-mingtsai:latest
    ports:
      - "8888:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /mnt/hdd0/no-mingtsai/data:/app/data
    restart: unless-stopped
